version: '2'
services:
  database:
    image: mariadb:10
    volumes:
      - mysql-data:/var/lib/mysql
    env_file: ./environments/database.env
    networks:
      - back-tier
    ports:
      - 13306:3306
  redis:
    image: redis:3-alpine
    volumes:
      - redis-data:/data
    networks:
      - back-tier
    ports:
      - 16379:6379
volumes:
  mysql-data:
    driver: local
  redis-data:
    driver: local
networks:
  back-tier:
    driver: bridge